### ISSUE TITLE
[stalk]Stalk does not include a part of nickname

### ISSUE THREAD

**Issue by daniel1302** [pingwindyktator/pybot#3]
If we stalk pingwindyktator we get below output:

```

12:25 < daniel1302> .stalk pingwindyktator
12:25 <@botpingwina> other nicks of pingwindyktator: {'stonoga', 'pingwindyktator', 'botpingwina_', 'botpingwina', 'pingwindyktator2'}

```

But if we stalk pingwin we dont get only question from bot :(

```

12:26 < daniel1302> .stalk pingwin
12:26 <@botpingwina> pingwin? what's that then?

```

**Comment by pingwindyktator** [comment]
That's how it had been designed. Please explain why it should behave like you described.

**Comment by hadson172** [comment]
This is huge time saving option for the client so probably it's worth your effort.
