### ISSUE TITLE
Is the manual up to date?

### ISSUE THREAD

**Issue by a-dubaj** [pingwindyktator/pybot#9]
Today I tried to run this project but it seems instruction is not up to date.

**Comment by pingwindyktator** [comment]
Can you share more details what gone wrong? I believe README is up to date.

**Comment by a-dubaj** [comment]
After running `docker build -t pybot .` Build is successful and tagged as: `Successfully tagged pybot:latest`
But after running: `./docker_run.sh`
I recived: 
`docker: Error response from daemon: error while creating mount source path '/etc/localtime': mkdir /etc/localtime: file exists.`

**Comment by pingwindyktator** [comment]
What OS are you running it on?

**Comment by a-dubaj** [comment]
Mojave MacOS

**Comment by pingwindyktator** [comment]
Please try to restart docker.
https://gerardnico.com/vm/docker/bind#error_while_creating_mount_source_pathfile_exists

**Comment by pingwindyktator** [comment]
Possible workaround is to remove `-v /etc/localtime:/etc/localtime:ro` mount from `docker_run.sh`. It's here just to synchronize timezone between host machine and docker container.
I will handle this issue shortly if restarting docker changes nothing.

**Comment by a-dubaj** [comment]
Also tried on CentOS 6.10 final: 
```
 ./docker_run.sh

Internal error occurred: FileNotFoundError: [Errno 2] No such file or directory: 'pybot.yaml'
Error report sent to sentry.io
```
